[theme]
primaryColor = "#1f77b4"
backgroundColor = "#111111"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "error"
